# Generated by Django 5.2 on 2026-02-14 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ORDER_PLACED', 'Order placed'), ('PAYMENT_RECEIVED', 'Payment received'), ('PREPARING_FOR_SHIPMENT', 'Preparing for shipment'), ('SENT', 'Sent'), ('ORDER_COMPLETED', 'Order completed')], default='ORDER_PLACED', max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=30, null=True)),
                ('was_placed', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.buyerprofile')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.shippingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_status', models.CharField(choices=[('NOT_SENT', 'NOT_SENT'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('AT_SORTING_FACILITY', 'At sorting facility'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('READY_FOR_PICKUP', 'Ready for pickup'), ('DELIVERED', 'Delivered'), ('COLLECTED', 'Collected'), ('DELIVERY_ATTEMPTED', 'Delivery attempted'), ('RETURNED_TO_SENDER', 'Returned to sender')], default='NOT_SENT', max_length=30)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='accounts.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.shipment')),
            ],
        ),
    ]
